[package]
name = "os"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = "0.5.2"
rlibc = "1.0.0"
bit_field = "0.10.2"
pc-keyboard = "0.7.0"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
