[package]
name = "os"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = "0.5.2"
rlibc = "1.0.0"
x86_64 = "0.14.2"
volatile = "0.2.6"
bitflags = "2.4.2"
bit_field = "0.10.2"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
pc-keyboard = "0.7.0"
