[unstable]
build-std = ["core", "compiler_builtins", "alloc" ]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-os.json"
rustflags = [ "-C", "link-arg=-Tlink.ld" ]

# [target.'cfg(target_os = "none")']
# runner = "bootimage runner"
